export const Button = {
    evenPaddingBlue: {
        alignItems: "center",
        appearance: "none",
        backgroundImage: "radial-gradient(100% 100% at 100% 0, #5adaff 0, #5468ff 100%)",
        border: "0",
        borderRadius: "6px",
        boxShadow: "rgba(45, 35, 66, .4) 0 2px 4px,rgba(45, 35, 66, .3) 0 7px 13px -3px,rgba(58, 65, 111, .5) 0 -3px 0 inset",
        boxSizing: "border-box",
        color: "#fff",
        cursor: "pointer",
        display: "inline-flex",
        height: "48px",
        justifyContent: "center",
        lineHeight: "1",
        listStyle: "none",
        overflow: "hidden",
        paddingLeft: "16px",
        paddingRight: "16px",
        position: "relative",
        textAlign: "left",
        textDecoration: "none",
        transition: "box-shadow .15s,transform .15s",
        userSelect: "none",
        touchAction: "manipulation",
        whiteSpace: "nowrap",
        willChange: "box-shadow,transform",
        fontSize: "18px",
        minWidth: "200px"
    },
    blue: {
        alignItems: "center",
        appearance: "none",
        backgroundImage: "radial-gradient(100% 100% at 100% 0, #5adaff 0, #5468ff 100%)",
        border: "0",
        borderRadius: "6px",
        boxShadow: "rgba(45, 35, 66, .4) 0 2px 4px,rgba(45, 35, 66, .3) 0 7px 13px -3px,rgba(58, 65, 111, .5) 0 -3px 0 inset",
        boxSizing: "border-box",
        color: "#fff",
        cursor: "pointer",
        display: "inline-flex",
        height: "48px",
        justifyContent: "center",
        lineHeight: "1",
        listStyle: "none",
        overflow: "hidden",
        paddingLeft: "16px",
        paddingRight: "16px",
        position: "relative",
        textAlign: "left",
        textDecoration: "none",
        transition: "box-shadow .15s,transform .15s",
        userSelect: "none",
        touchAction: "manipulation",
        whiteSpace: "nowrap",
        willChange: "box-shadow,transform",
        fontSize: "18px"
    },
    smallBlue: {
        backgroundColor: "#0095ff",
        border: "1px solid transparent",
        borderRadius: "3px",
        boxShadow: "rgba(255, 255, 255, .4) 0 1px 0 0 inset",
        boxSizing: "border-box",
        color: "#fff",
        cursor: "pointer",
        display: "inline-block",
        fontSize: "13px",
        fontWeight: "400",
        lineHeight: "1.15385",
        margin: "0",
        outline: "none",
        padding: "8px .8em",
        position: "relative",
        textAlign: "center",
        textDecoration: "none",
        userSelect: "none",
        touchAction: "manipulation",
        verticalAlign: "baseline",
        whiteSpace: "nowrap"
    },
    smallRed: {
        backgroundColor: "#e83a09",
        border: "1px solid transparent",
        borderRadius: "3px",
        boxShadow: "rgba(255, 255, 255, .4) 0 1px 0 0 inset",
        boxSizing: "border-box",
        color: "#fff",
        cursor: "pointer",
        display: "inline-block",
        fontSize: "13px",
        fontWeight: "400",
        lineHeight: "1.15385",
        margin: "0",
        outline: "none",
        padding: "8px .8em",
        position: "relative",
        textAlign: "center",
        textDecoration: "none",
        userSelect: "none",
        touchAction: "manipulation",
        verticalAlign: "baseline",
        whiteSpace: "nowrap"
    }
}